# Site settings
title: Dungeon World
email: joeysmith@gmail.com
description: "A few friends and I are trying out Dungeon World. I will be writing recaps of our sessions and posting them here."
baseurl: ""
url: "http://dw.joeysmith.com/"
github_username:  tml

# Build settings
markdown: kramdown
permalink: pretty
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
